export const listProcut = [
  { id: 1, name: 'A', parameters: 'Parameter 1, Parameter 2', visibility: true },
  { id: 2, name: 'B', parameters: 'Parameter 3, Parameter 4', visibility: false },
  { id: 3, name: 'C', parameters: 'Parameter 5, Parameter 6', visibility: true },
  { id: 4, name: 'D', parameters: 'Parameter 7, Parameter 8', visibility: false },
  { id: 5, name: 'E', parameters: 'Parameter 9, Parameter 10', visibility: true },
  { id: 6, name: 'F', parameters: 'Parameter 11, Parameter 12', visibility: false },
  { id: 7, name: 'G', parameters: 'Parameter 13, Parameter 14', visibility: true },
  { id: 8, name: 'H', parameters: 'Parameter 15, Parameter 16', visibility: false },
  { id: 9, name: 'I', parameters: 'Parameter 17, Parameter 18', visibility: true },
  { id: 10, name: 'J', parameters: 'Parameter 19, Parameter 20', visibility: false },
  { id: 11, name: 'K', parameters: 'Parameter 21, Parameter 22', visibility: true },
  { id: 12, name: 'L', parameters: 'Parameter 23, Parameter 24', visibility: false },
  { id: 13, name: 'M', parameters: 'Parameter 25, Parameter 26', visibility: true },
  { id: 14, name: 'N', parameters: 'Parameter 27, Parameter 28', visibility: false },
  { id: 15, name: 'O', parameters: 'Parameter 29, Parameter 30', visibility: true },
  { id: 16, name: 'P', parameters: 'Parameter 31, Parameter 32', visibility: false },
  { id: 17, name: 'Q', parameters: 'Parameter 33, Parameter 34', visibility: true },
  { id: 18, name: 'R', parameters: 'Parameter 35, Parameter 36', visibility: false },
  { id: 19, name: 'S', parameters: 'Parameter 37, Parameter 38', visibility: true },
  { id: 20, name: 'T', parameters: 'Parameter 39, Parameter 40', visibility: false },
];